### ISSUE TITLE
Document dependencies better

### ISSUE THREAD

**Issue by AdrianKoshka** [linuxlite/litewelcome#5]
While this is most likely a **very** simple application, documenting some of the general, or even all of the depends in the `README.md` file would help future developers that join the team know what they're dealing with. Feel free to assign me with this issue.

**Comment by mertcelen** [comment]
I totally agree with you (even it's a year late reply).

It didn't worked out of box to use it with Debian Stretch , Webkit 3.0 dependency was missing.
It can be solved install this library
`apt install gir1.2-webkit-3.0`
